<a href="https://colab.research.google.com/github/HamedFarahani89/AI-Lab/blob/main/Getting_started_pytorch_DUDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import torch.nn as nn
import matplotlib.pyplot as plt

matrix transpose

$$
A^T
$$

In [2]:
# repeat for a matrix
tM = torch.tensor([ [1,2,3,4],[5,6,7,8] ])
print(tM), print(' ')

# transpose it
print(tM.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])


 dot product

 $$
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i \cdot b_i
$$


In [3]:
# create a vector
tv1 = torch.tensor([1,1,3,4])
tv2 = torch.tensor([-2,1,0,-1])


# Dot product using a function
dot_product_function = torch.dot(tv1, tv2)
print("Dot product using a function:", dot_product_function)

# Dot product using computation
dot_product_computation = torch.sum(tv1 * tv2)
print("Dot product using computation:", dot_product_computation)


# Computing the dot product
dot_product = 1 * -2 + 1 * 1 + 3 * 0 + 4 * -1
print("According to theory, the dot product is:", dot_product)


Dot product using a function: tensor(-5)
Dot product using computation: tensor(-5)
According to theory, the dot product is: -5


Matrix multiplication

$$
C = A \times B
$$

In [4]:
# Create some random matrices
A = torch.randn(3, 4)
B = torch.randn(4, 5)

# Checking if numpy array is compatible with torch tensor
# Also, dimensions should be correct
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype=torch.float)

# Try some multiplications
# print(np.round(A @ B, 2)), print(' ')
# print(np.round(A @ B.T, 2)), print(' ')
print(np.round(A @ C1, 2)), print(' ')
print(np.round(A @ C2, 2))


tensor([[ 3.6900,  2.0200, -1.8200, -1.7600,  0.1100,  2.0300, -0.1200],
        [-4.3500,  1.3800, -2.0000,  0.8600, -1.2100, -1.3500, -0.1000],
        [ 3.3200, -1.9000,  2.4800,  0.3500,  1.6800,  1.9800,  0.3200]],
       dtype=torch.float64)
 
tensor([[ 3.6900,  2.0200, -1.8200, -1.7600,  0.1100,  2.0300, -0.1200],
        [-4.3500,  1.3800, -2.0000,  0.8600, -1.2100, -1.3500, -0.1000],
        [ 3.3200, -1.9000,  2.4800,  0.3500,  1.6800,  1.9800,  0.3200]])


Softmax

$$
\text{softmax}(x)_i = \frac{e^{x_i}}{\sum_j e^{x_j}}
$$


In [5]:
z = torch.tensor([-2,1,.02,-1])

# create an instance of the softmax activation class
softfun = nn.Softmax(dim=0)

# then apply the data to that function
sigmaT = softfun( torch.Tensor(z) )

# now we get the results
print(sigmaT)

print('To check the first element softmax is ', torch.exp(torch.tensor(-2.0))/torch.sum(torch.exp(z)))

tensor([0.0319, 0.6408, 0.2405, 0.0867])
To check the first element softmax is  tensor(0.0319)


Entropy and cross-entropy

$$
H(X) = -\sum_{i=1}^{n} p(x_i) \log{p(x_i)}
$$

$$
H(p, q) = -\sum_{i=1}^{n} p(x_i) \log{q(x_i)}
$$


In [6]:
# the correct way to compute entropy
P = [.25,.75]

H = 0
for p in P:
  H -= p*np.log(p)

print('Correct entropy: ' + str(H))

Correct entropy: 0.5623351446188083


In [7]:
# note: all probs must sum to 1!
p = [   1.,0.   ] # sum=1
q = [ .25,.75 ] # sum=1

H = 0
for i in range(len(p)):
  H -= p[i]*np.log(q[i])

print('Cross entropy: ' + str(H))

Cross entropy: 1.3862943611198906


In [8]:
import torch.nn.functional as F

# Define the ground truth probabilities (p) and predicted probabilities (q)
p = [1., 0.]  # Ground truth probabilities
q = [0.25, 0.75]  # Predicted probabilities

# Convert lists to PyTorch tensors
p_tensor = torch.tensor(p, dtype=torch.float32)
q_tensor = torch.tensor(q, dtype=torch.float32)

# Compute binary cross-entropy
loss = F.binary_cross_entropy(torch.tensor(q_tensor), torch.tensor(p_tensor))

print(loss.item())  # Print the loss value


1.3862943649291992


<ipython-input-8-ddf000a37e30>:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  loss = F.binary_cross_entropy(torch.tensor(q_tensor), torch.tensor(p_tensor))
